services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # Install deps at container start to populate the named node_modules volume, then run Strapi in dev mode
    command: sh -c "yarn install && yarn develop"

    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: cloud-sql-proxy
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: development
    volumes:
      - ./:/opt/app
      - strapi_node_modules:/opt/app/node_modules
    ports:
      - "1337:1337"
    depends_on:
      - cloud-sql-proxy

  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:latest
    container_name: cloud-sql-proxy
    restart: unless-stopped
    command:
      - "/cloud_sql_proxy"
      - "-instances=${GCP_INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:5432"
      - "-credential_file=/gcp/service-account-key.json"
    volumes:
      - /home/chris/strapi/gcp:/gcp:ro
    ports:
      - "5432:5432"

volumes:
  strapi_node_modules:
